# IMPORTS
from dotenv import load_dotenv
from flask import Flask, render_template, request
from playhouse.shortcuts import model_to_dict
from .database import *

# APP INITIALIZATION
load_dotenv()
app = Flask(__name__)

# APP HOOKS
db = database.db

# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()

# APP ROUTES
@app.route('/')
def index():
    return render_template("index.html")

@app.route('/about')
def about():
    return render_template("about.html")